export const ScreenName = {
  SplashScreen: 'SplashScreen',
  TypesSignIn: 'TypesSignIn',
  RegisterScreen: 'RegisterScreen',
  LoginScreen: 'LoginScreen',
  BottomBar: 'BottomBar',
  HomeScreen: 'HomeScreen',
  ExploreScreen: 'ExploreScreen',
  LibraryScreen: 'LibraryScreen',
  ProfileScreen: 'ProfileScreen',
  FillProfile: 'FillProfile',
  CreateNewPin: 'CreateNewPin',
  SetFingerprint: 'SetFingerprint',
  FollowArtists: 'FollowArtists',
};
