export const titles = {
    introduction: 'Listen to the best music everyday with',
    now: 'now!',
    hear_me: 'HearMe',
    have_nice: 'Have a nice day!',
    rate_me: 'Rate me 5 stars 🥰',
    get_started: 'Get Started',
    lets_you_in: 'Let\'s you in',
    continue_with_fb: 'Continue with Facebook',
    continue_with_Gg: 'Continue with Google',
    continue_with_Ap: 'Continue with Apple',
    sign_in_pass: 'Sign in with password',
    sign_in: 'Sign in',
    not_have_account: 'Don\'t have an account?',
    sign_up: 'Sign up',
    create_account: 'Create Your Account',
    email: 'Email',
    password: 'Password',
    remember_me: 'Remember me',
    or: 'or',
    or_continue_with: 'or continue with',
    have_account: 'Already have an account?',
    login: 'Login to Your Account',
    forgot_pass_question: 'Forgot the password?',
    fill_profile: 'Fill Your Profile',
    full_name: 'Full Name',
    nickname: 'Nickname',
    dob: 'Date of Birth',
    phone_number: 'Phone Number',
    skip: 'Skip',
    continue: 'Continue',
    create_pin: 'Create New PIN',
    add_pin_number: 'Add a PIN number to make your account more secure.',
    set_fingerprint: 'Set Your Fingerprint',
    add_fingerprint: 'Add a fingerprint to make your account more secure.',
    ask_add_fingerprint: 'Please put your finger on the fingerprint scanner to get started.',
    follow_artists: 'Follow Artists',
    follow: 'Follow',
    follow_description: 'Follow your favorite artists. Or you can skip it for now.',
    forgot_pass: 'Forgot Password',
    select_type_contact: 'Select which contact details should we use to reset your password',
    via_sms: 'via SMS',
    via_email: 'via Email',
    code_description: 'Code has been send to',
    resend_code: 'Resend code in',
    verify: 'Verify',
    create_new_password: 'Create New Password',
    create_new_pass_des: 'Create Your New Password',
    congratulations: 'Congratulations!',
    your_account_ready_use: 'Your account is ready to use. You will be redirected to the Home page in a few seconds.',
    good_morning: 'Good morning',
    good_evening: 'Good evening',
    good_afternoon: 'Good afternoon',
    trending_now: 'Trending Now',
    see_all: 'See All',
    popular_artists: 'Popular Artists',
    top_charts: 'Top Charts',
    home: 'Home',
    explore: 'Explore',
    library: 'Library',
    profile: 'Profile',
    notifications: 'Notifications',
    songs: 'Songs',
    podcasts: 'Podcasts',
    new_music_today: 'New Music Release Today',
    new_podcast_today: 'New Podcasts Release Today',
    browse_all: 'Browse All',
    artist_song_podcast: 'Artists, Songs, Podcasts & More',
    weekly_album: 'Weekly Album Charts',
    weekly_song: 'Weekly Song Charts',
    daily_viral: 'Daily Viral Charts',
    popular_podcasts: 'Popular Podcasts',
    categories: 'Categories',
}